name: Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "setup pnpm"
        uses: "pnpm/action-setup@v4"

      - name: "setup node"
        uses: "actions/setup-node@v4"
        with:
          node-version: 20

      - name: "Install"
        run: "pnpm install"

      # 压缩图片
      - name: "图片压缩"
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          jpegQuality: '80'
          pngQuality: '80'
          webpQuality: '80'
          ignorePaths: 'node_modules/**'
          compressOnly: true

      - name: "MarkdownLint Check"
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          fix: true
          globs: 'docs*/**/*.md'

      - name: "Build"
        run: "pnpm run build"
